### ISSUE TITLE
Mix deploy fails when there are no "publish" options in config

### ISSUE THREAD

**Issue by oscarcolome** [rubencaro/bottler#7]
When I try to deploy an elixir app using Bottler, it gives me the following error: 

** (MatchError) no match of right hand side value: nil
    (bottler) lib/mix/tasks/deploy.ex:26: Mix.Tasks.Deploy.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2

After some digging, I found out that it expects a "publish" option in the app's config. 
Is this option mandatory? Shouldn't it be optional and return :ok if it doesn't find it?

**Comment by rubencaro** [comment]
@cles will know the answer, right?

**Comment by cles** [comment]
Fixed by https://github.com/rubencaro/bottler/pull/9
